apiVersion: v1
kind: Service
metadata:
  name: hadoop-master
spec:
  type: NodePort
  selector:
    app: hadoop-master
  ports:
    - name: webhdfs
      port: 50070
      targetPort: 50070
      # nodePort: 30070 
    - name: yarn
      port: 8088
      targetPort: 8088
      # nodePort: 30088 
    - name: fs
      port: 9000
      targetPort: 9000
      # nodePort: 30090 

apiVersion: v1
kind: Service
metadata:
  name: hadoop-master-headless
spec:
  type: ClusterIP
  clusterIP: None  # Headless Service를 설정
  selector:
    app: hadoop-master
  ports:
    - name: webhdfs
      port: 50070
      targetPort: 50070
    - name: yarn
      port: 8088
      targetPort: 8088
    - name: fs
      port: 9000
      targetPort: 9000
    - name: ssh
      port: 22
      targetPort: 22
