apiVersion: v1
kind: Service
metadata:
  name: hadoop-worker-nodeport
spec:
  type: NodePort
  selector:
    app: hadoop-worker
  ports:
    - name: datanode
      port: 50075
      targetPort: 50075
      # nodePort: 31075

apiVersion: v1
kind: Service
metadata:
  name: hadoop-worker-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hadoop-worker
  ports:
    - name: datanode
      port: 50075
      targetPort: 50075
