apiVersion: v1
kind: Secret
metadata:
  name: ssh-secret
type: Opaque
data:
  id_rsa: {{ .Files.Get "../ssh-secret/hadoop_rsa" | b64enc | quote }}
  id_rsa.pub: {{ .Files.Get "../ssh-secret/hadoop_rsa.pub" | b64enc | quote }}
  authorized_keys: {{ .Files.Get "../ssh-secret/hadoop_rsa.pub" | b64enc | quote }}

